//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long id { get; set; }
        public string nation { get; set; }
        public string city { get; set; }
        public string title { get; set; }
        public string localTitle { get; set; }
        public string img { get; set; }
        public string room { get; set; }
        public string dinner { get; set; }
        public string address { get; set; }
        public string latlng { get; set; }
        public string contact { get; set; }
        public string wifi { get; set; }
        public string parking { get; set; }
        public string reception { get; set; }
        public string kitchen { get; set; }
        public string tips { get; set; }
    }
}
