//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenic
    {
        public long id { get; set; }
        public string nation { get; set; }
        public string city { get; set; }
        public string title { get; set; }
        public string localTitle { get; set; }
        public string img { get; set; }
        public string latlng { get; set; }
        public string localAdd { get; set; }
        public Nullable<System.DateTime> openAt { get; set; }
        public Nullable<System.DateTime> closeAt { get; set; }
        public string ticket { get; set; }
        public string tips { get; set; }
    }
}
