//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public long id { get; set; }
        public long RelatedId { get; set; }
        public string RelatedType { get; set; }
        public long day { get; set; }
        public int position { get; set; }
        public long tripId { get; set; }
        public long locationId { get; set; }
    
        public virtual ComboLocation ComboLocation { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
