//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayLocation
    {
        public int id { get; set; }
        public int RelatedId { get; set; }
        public string RelatedType { get; set; }
        public int day { get; set; }
        public int position { get; set; }
        public int day_id { get; set; }
        public int trip_id { get; set; }
        public int location_id { get; set; }
    
        public virtual ComboLocation ComboLocation { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual TripDay TripDay { get; set; }
    }
}
