//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dining
    {
        public long id { get; set; }
        public string nation { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string title { get; set; }
        public string dishes { get; set; }
        public string img { get; set; }
        public string latlng { get; set; }
        public string reach { get; set; }
        public string address { get; set; }
        public string recommendedDishes { get; set; }
        public string tips { get; set; }
    }
}
