//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationImage
    {
        public int id { get; set; }
        public int location_id { get; set; }
        public string name { get; set; }
        public string memo { get; set; }
    
        public virtual ComboLocation ComboLocation { get; set; }
    }
}
