//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DctsEntities : DbContext
    {
        public DctsEntities()
            : base("name=DctsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dining> Dinings { get; set; }
        public DbSet<Hotel> Hotels { get; set; }
        public DbSet<Scenic> Scenics { get; set; }
        public DbSet<Trip> Trips { get; set; }
        public DbSet<Day> Days { get; set; }
    }
}
