//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DctsEntities : DbContext
    {
        public DctsEntities()
            : base("name=DctsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Trip> Trips { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Nation> Nations { get; set; }
        public DbSet<ComboLocation> ComboLocations { get; set; }
        public DbSet<DayLocation> DayLocations { get; set; }
        public DbSet<TripDay> TripDays { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<LocationImage> LocationImages { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TripCustomer> TripCustomers { get; set; }
    }
}
