//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDay
    {
        public TripDay()
        {
            this.DayLocations = new HashSet<DayLocation>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int id { get; set; }
        public int trip_id { get; set; }
        public string title { get; set; }
        public int day { get; set; }
        public string memo { get; set; }
        public string tips { get; set; }
        public string schedule { get; set; }
        public int cover_id { get; set; }
        public string cities { get; set; }
        public string image_path { get; set; }
    
        public virtual ICollection<DayLocation> DayLocations { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
